# Author: Scott Haskell
# Company: Splunk Inc.
# Date: 2016-10-21
#
# The MIT License
#
# Copyright (c) 2016 Scott Haskell, Splunk Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 
hec:
    # Splunk HEC host or VIP to load balanced HEC instances
    host: 172.17.0.5
    # HEC port - default 8088
    port: 8088
    # App specific UUID used by HEC - generate your own using 'uuidgen' in Linux
    channel: 408c8da1-b9b1-460b-aeb4-56426865bca1
    # HEC token for your input
    token: B373AE38-902D-4DFC-87BE-43E0E5D5AB01
    # Set input sourcetype
    sourcetype: access_combined
    # Set input source
    source: hec:nginx 
    # Verify SSL certificate
    verify_ssl: False
kafka:
    # List of Kafka brokers <host>:<port>
    brokers:
        - 172.17.0.2:9092
        - 172.17.0.3:9093
        - 172.17.0.4:9094
    # Zookeeper hostname/ip
    zookeeper_server: localhost
    # Zookeeper port
    zookeeper_port: 2181
    # Arbitrary group name used for coordinating workers in topic
    consumer_group: shark
    # Kafka topic name
    topic: nginx
    # If you have librdkafka installed and pykafka was built against it, use this to increase speed
    # Valid values: True or False
    use_rdkafka: True
general:
    # Set to number of partitions in the topic for maximum parallelism and throughput
    # Do not exceed number of cores on your system - spread across multiple machines
    # Do not set workers across all instances > # of partitions in topic - will result in idle wokrers
    workers: 3
    # Number of messages to send to Splunk in each HTTP call to HEC
    # Data will not be sent until there is >= batch_size events in the topic.
    # Increase or decrease depending on activity in topic. 
    # WARNING: If you set this to 1 it will increase the activity on your network and decrease
    # throughput to the HEC.
    batch_size: 1024
network:
    # Backoff policy settings
    # Number of retry attempts before quitting
    retry_attempts: 5
    # Sleeptime between retries
    sleeptime: 60
    # maximum sleeptime
    max_sleeptime: 300 
    # sleep time multiplier applied to each iteration
    sleepscale: 1.5
    # random jitter introduced to each iteration, random between [-jitter, +jitter]
    jitter: 5 
logging:
    # (debug|info|warning|error|critical)
    loglevel: debug
